name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ] # Change en 'master' si ta branche s'appelle master

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OBLIGATOIRE : Télécharge tout l'historique pour éviter l'erreur 'shallow update'

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://FloridaTOVANA:$HF_TOKEN@huggingface.co/spaces/FloridaTOVANA/wallmart-v2 main:main