name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ] # Change en 'master' si ta branche principale s'appelle master

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Mis à jour vers v4 pour éliminer l'avertissement Node.js

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://FloridaTOVANA:$HF_TOKEN@huggingface.co/spaces/FloridaTOVANA/Walmart_marketing_dashboard main